import { Facebook, Instagram, Mail, MapPin, Phone, ExternalLink, MessageCircle } from 'lucide-react'
import { siteConfig } from '../config'
import { useLanguage } from '../i18n'
import { scrollToSection } from '../utils/navigation'
export default function Footer(){
  const { t } = useLanguage()
  return <><footer id="contact" className="scroll-mt-24 bg-forest-950 text-parchment py-16"><div className="max-w-7xl mx-auto px-6 md:px-10"><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-10 pb-12 border-b border-parchment/10"><div className="lg:col-span-1"><p className="font-display text-2xl">Loleza <span className="text-gold-400">Ridge</span></p><p className="text-parchment/50 text-sm leading-relaxed mt-4">{t('A quiet lodge above the Mbeya escarpment, surrounded by coffee terraces and Southern Highlands skies.')}</p></div><div><p className="footer-title">{t('Explore')}</p><div className="grid grid-cols-2 gap-y-3 text-sm text-parchment/55">{[['rooms','Rooms'],['about','About'],['amenities','Amenities'],['experiences','Experiences'],['gallery','Gallery'],['offers','Offers'],['faq','FAQ'],['location','Location']].map(([id,label]) => <a key={id} href={`#${id}`} onClick={(e)=>{e.preventDefault();scrollToSection(id)}} className="hover:text-gold-400 transition-colors">{t(label)}</a>)}</div></div><div><p className="footer-title">{t('Contact')}</p><div className="space-y-3 text-sm text-parchment/55">{siteConfig.phone ? <a href={`tel:${siteConfig.phone}`} className="flex gap-2 hover:text-gold-400"><Phone className="w-4"/>{siteConfig.phone}</a> : <span className="flex gap-2 text-parchment/30"><Phone className="w-4"/> {t('Add phone number')}</span>}{siteConfig.email ? <a href={`mailto:${siteConfig.email}`} className="flex gap-2 hover:text-gold-400"><Mail className="w-4"/>{siteConfig.email}</a> : <span className="flex gap-2 text-parchment/30"><Mail className="w-4"/> {t('Add email address')}</span>}<span className="flex gap-2"><MapPin className="w-4 shrink-0"/>{siteConfig.location}</span></div></div><div><p className="footer-title">{t('Follow')}</p><div className="flex gap-3">{siteConfig.social.instagram ? <a href={siteConfig.social.instagram} target="_blank" rel="noreferrer" className="social" aria-label="Instagram"><Instagram/></a> : null}{siteConfig.social.facebook ? <a href={siteConfig.social.facebook} target="_blank" rel="noreferrer" className="social" aria-label="Facebook"><Facebook/></a> : null}{siteConfig.social.tripadvisor ? <a href={siteConfig.social.tripadvisor} target="_blank" rel="noreferrer" className="social" aria-label="Tripadvisor"><ExternalLink/></a> : null}</div><p className="text-xs text-parchment/40 mt-5">{t('Instagram · Facebook · TripAdvisor · Booking.com')}</p>{siteConfig.whatsapp ? <a href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mt-5 text-sm text-gold-400 hover:text-gold-300"><MessageCircle className="w-4"/> {t('WhatsApp the lodge')}</a> : null}</div></div><div className="flex flex-col lg:flex-row justify-between gap-5 pt-6 text-xs text-parchment/35">
  <span>{t('© 2026 Loleza Ridge Lodge. All rights reserved.')}</span>
  <nav aria-label="Legal" className="flex flex-wrap gap-x-4 gap-y-2">
    <a href="#/terms" className="hover:text-gold-400">{t('Terms & Conditions')}</a>
    <a href="#/privacy" className="hover:text-gold-400">{t('Privacy Policy')}</a>
    <a href="#/cookies" className="hover:text-gold-400">{t('Cookie Policy')}</a>
    <a href="#/accessibility" className="hover:text-gold-400">{t('Accessibility')}</a>
  </nav>
</div></div></footer>{siteConfig.whatsapp && <a href={`https://wa.me/${siteConfig.whatsapp}`} target="_blank" rel="noreferrer" className="float-wa fixed bottom-5 right-5 z-40 bg-[#25D366] text-white w-14 h-14 rounded-full flex items-center justify-center shadow-xl" aria-label="Chat on WhatsApp"><MessageCircle className="w-6 h-6"/></a>}</>}
